### ISSUE TITLE
Adapter refactoring

### ISSUE THREAD

**Issue by g4s8** [artipie/maven-adapter#54]
Refactor maven adapter base interfaces and entry points:
 - it should be reactive - no support for `InputStream` and `OutputStream`, only `Publisher<ByteBuffer>` from reactivestreams.org
 - Entry point class should encapsulate `Storage` interface from `artipie/asto` dependency and use it to generate metadata by key, e.g. `new Maven(storage).update(new Key.From("org/artipie/maven-adapter"))`

Ask me if something is not clear.

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
I'm not managing `artipie/maven-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
I'm not managing `artipie/maven-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/maven-adapter/issues/54#issuecomment-593844826))

@g4s8 The job [#54](https://github.com/artipie/maven-adapter/issues/54) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/72cd3414-dd05-4289-8dde-5b0b47bd6f44); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/artipie/maven-adapter/issues/54#issuecomment-594460360))

@g4s8 Boost 4x was set for [#54](https://github.com/artipie/maven-adapter/issues/54)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #55 merge

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#56](https://github.com/artipie/maven-adapter/issues/56), [#57](https://github.com/artipie/maven-adapter/issues/57), [#58](https://github.com/artipie/maven-adapter/issues/58) are still not solved.

**Comment by g4s8** [comment]
@paulodamaso fixed by #55 PR

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#56](https://github.com/artipie/maven-adapter/issues/56), [#58](https://github.com/artipie/maven-adapter/issues/58), [#60](https://github.com/artipie/maven-adapter/issues/60) are still not solved; solved: [#57](https://github.com/artipie/maven-adapter/issues/57).

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#56](https://github.com/artipie/maven-adapter/issues/56), [#60](https://github.com/artipie/maven-adapter/issues/60), [#62](https://github.com/artipie/maven-adapter/issues/62) are still not solved; solved: [#57](https://github.com/artipie/maven-adapter/issues/57), [#58](https://github.com/artipie/maven-adapter/issues/58).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#56](https://github.com/artipie/maven-adapter/issues/56), [#62](https://github.com/artipie/maven-adapter/issues/62) are still not solved; solved: [#57](https://github.com/artipie/maven-adapter/issues/57), [#58](https://github.com/artipie/maven-adapter/issues/58), [#60](https://github.com/artipie/maven-adapter/issues/60).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#56](https://github.com/artipie/maven-adapter/issues/56) is still not solved; solved: [#57](https://github.com/artipie/maven-adapter/issues/57), [#58](https://github.com/artipie/maven-adapter/issues/58), [#60](https://github.com/artipie/maven-adapter/issues/60), [#62](https://github.com/artipie/maven-adapter/issues/62).

**Comment by 0pdd** [comment]
@g4s8 all 5 puzzles are solved here: [#56](https://github.com/artipie/maven-adapter/issues/56), [#57](https://github.com/artipie/maven-adapter/issues/57), [#58](https://github.com/artipie/maven-adapter/issues/58), [#60](https://github.com/artipie/maven-adapter/issues/60), [#62](https://github.com/artipie/maven-adapter/issues/62).
